from aenum import Enum

# CONSTANTS WITH DESCRIPTIVE NAMES
NAMEOF_DATABASE_SWARM_KEYSPACE = 'KS_SWARM'
NAMEOF_DATABASE_REPLICATION_STRATEGY = 'SimpleStrategy'
NAMEOF_DATABASE_SWARM_TABLE_ACTIVE_NODES = 'Active_Nodes'
NUMBEROF_DATABASE_REPLICATION_FACTOR = '1'

NAMEOF_DATABASE_FIELD_NODE_UUID = 'Node_UUID'
TYPEOF_DATABASE_FIELD_NODE_UUID = 'txt'

NAMEOF_DATABASE_FIELD_NODE_SWARM_ID = 'Node_Swarm_ID'
TYPEOF_DATABASE_FIELD_NODE_SWARM_ID = 'txt'


NAMEOF_DATABASE_FIELD_NODE_SWARM_IP = 'Swarm_IP'
TYPEOF_DATABASE_FIELD_NODE_SWARM_IP = 'text'

NAMEOF_DATABASE_FIELD_NODE_SWARM_MAC = 'Swarm_MAC'
TYPEOF_DATABASE_FIELD_NODE_SWARM_MAC = 'text'

NAMEOF_DATABASE_FIELD_NODE_PHYSICAL_MAC = 'Physical_MAC'
TYPEOF_DATABASE_FIELD_NODE_PHYSICAL_MAC = 'text'

NAMEOF_DATABASE_FIELD_NODE_CURRENT_AP = 'Node_Current_AP'
TYPEOF_DATABASE_FIELD_NODE_CURRENT_AP = 'text'

NAMEOF_DATABASE_FIELD_NODE_CURRENT_SWARM = 'Node_Current_SWARM'
TYPEOF_DATABASE_FIELD_NODE_CURRENT_SWARM = 'text'

NAMEOF_DATABASE_FIELD_NODE_SWARM_STATUS = 'Node_Swarm_Status'
TYPEOF_DATABASE_FIELD_NODE_SWARM_STATUS = 'text'

NAMEOF_DATABASE_FIELD_LAST_UPDATE_TIMESTAMP = 'Last_Update_Timestamp'
TYPEOF_DATABASE_FIELD_LAST_UPDATE_TIMESTAMP = 'timestamp'


class SWARM_STATUS(Enum):
    JOINED  = 'Joined'
    PENDING = 'Pending'
    LEFT    = 'Left'
