from aenum import Enum

# CONSTANTS WITH DESCRIPTIVE NAMES
NAMEOF_DATABASE_SWARM_KEYSPACE = 'KS_SWARM'
NAMEOF_DATABASE_REPLICATION_STRATEGY = 'SimpleStrategy'

NAMEOF_DATABASE_SWARM_TABLE = 'Swarm_Table'
NAMEOF_DATABASE_ADDRESS_RESOLUTION_TABLE = 'ART'

NUMBEROF_DATABASE_REPLICATION_FACTOR = '1'

NAMEOF_DATABASE_FIELD_NODE_UUID = 'UUID'
TYPEOF_DATABASE_FIELD_NODE_UUID = 'text'

NAMEOF_DATABASE_FIELD_NODE_SWARM_ID = 'virt_ID'
TYPEOF_DATABASE_FIELD_NODE_SWARM_ID = 'int'


NAMEOF_DATABASE_FIELD_NODE_SWARM_IP = 'virt_IP'
TYPEOF_DATABASE_FIELD_NODE_SWARM_IP = 'text'

NAMEOF_DATABASE_FIELD_AP_PORT = 'AP_PORT'
TYPEOF_DATABASE_FIELD_AP_PORT = 'int'

NAMEOF_DATABASE_FIELD_NODE_SWARM_MAC = 'virt_Mac'
TYPEOF_DATABASE_FIELD_NODE_SWARM_MAC = 'text'

NAMEOF_DATABASE_FIELD_NODE_PHYSICAL_MAC = 'Phys_MAC'
TYPEOF_DATABASE_FIELD_NODE_PHYSICAL_MAC = 'text'

NAMEOF_DATABASE_FIELD_NODE_CURRENT_AP = 'Current_AP'
TYPEOF_DATABASE_FIELD_NODE_CURRENT_AP = 'text'

NAMEOF_DATABASE_FIELD_NODE_CURRENT_SWARM = 'Current_SWARM'
TYPEOF_DATABASE_FIELD_NODE_CURRENT_SWARM = 'int'

NAMEOF_DATABASE_FIELD_NODE_SWARM_STATUS = 'Status'
TYPEOF_DATABASE_FIELD_NODE_SWARM_STATUS = 'text'

NAMEOF_DATABASE_FIELD_LAST_UPDATE_TIMESTAMP = 'Last_Update'
TYPEOF_DATABASE_FIELD_LAST_UPDATE_TIMESTAMP = 'timestamp'


class SWARM_STATUS(Enum):
    JOINED  = 'Joined'
    PENDING = 'Pending'
    LEFT    = 'Left'
    DISCONNECTED = 'Disconnected'
