from lib.db.defines import *

# DATABASE QUERIES
QUERY_DATABASE_CREATE_KEYSPACE = f"""\
CREATE KEYSPACE IF NOT EXISTS {NAMEOF_DATABASE_SWARM_KEYSPACE} \
WITH REPLICATION = {{ \
'class' : '{NAMEOF_DATABASE_REPLICATION_STRATEGY}', \
'replication_factor' : '{NUMBEROF_DATABASE_REPLICATION_FACTOR}' }}; \
                                """
                                
QUERY_DATABASE_CREATE_TABLE =  f"""
CREATE TABLE IF NOT EXISTS {NAMEOF_DATABASE_SWARM_KEYSPACE}.{NAMEOF_DATABASE_SWARM_TABLE_ACTIVE_NODES}
(
{NAMEOF_DATABASE_FIELD_NODE_SWARM_ID} {TYPEOF_DATABASE_FIELD_NODE_SWARM_ID} PRIMARY KEY,
{NAMEOF_DATABASE_FIELD_NODE_UUID} {TYPEOF_DATABASE_FIELD_NODE_UUID},
{NAMEOF_DATABASE_FIELD_NODE_CURRENT_AP} {TYPEOF_DATABASE_FIELD_NODE_CURRENT_AP},
{NAMEOF_DATABASE_FIELD_NODE_SWARM_STATUS} {TYPEOF_DATABASE_FIELD_NODE_SWARM_STATUS},
{NAMEOF_DATABASE_FIELD_NODE_SWARM_IP} {TYPEOF_DATABASE_FIELD_NODE_SWARM_IP},
{NAMEOF_DATABASE_FIELD_NODE_SWARM_MAC} {TYPEOF_DATABASE_FIELD_NODE_SWARM_MAC},
{NAMEOF_DATABASE_FIELD_LAST_UPDATE_TIMESTAMP} {TYPEOF_DATABASE_FIELD_LAST_UPDATE_TIMESTAMP}
);
"""
